version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: pos
    volumes:
      - ./wp-data:/var/www/html


  db:
    image: mysql/mysql-server:8.0
    ports:
      - 8082:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pos
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345678
